### ISSUE TITLE
Allow picture-entity (or other) cards inside glance cards

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/ui-schema#133] opened 2018-07-24 18:47 UTC
Glance cards allow dividing the row nicely in smaller groups. However, glance card is currently limited to only entities. It will be nice if we can allow using other cards inside glance. That will make something like the following possible (assuming the buttons can be assigned to service call):
![image](https://user-images.githubusercontent.com/18319734/43159302-f74b17e6-8f4f-11e8-8fbe-90867c1a1b65.png)

I tried picture-entity in a `horizontal-stack` and the result is not ideal (as they appear as separate cards):
![image](https://user-images.githubusercontent.com/18319734/43159398-3ffe8e50-8f50-11e8-8cfe-638f1fb70a77.png)

**Comment by balloob** [comment] 2018-07-25 09:01
I don't think that we should abuse glance card for this. I also think that if the use case is only remotes, we should consider adding a remote card?

**Comment by iantrich** [comment] 2018-07-26 13:07
Picture Elements solved this use case for me, but was not nearly as easy to create.

If we ever get to the point where we have a UI editor for picture elements that allows for drag and drop editing, which I would think is one of our end goals, I think a specific card is unnecessary

**Comment by arsaboo** [comment] 2018-07-27 18:22
@balloob the remote was just an example. I think there are other uses for this. Consider another example, here's a glance card I created for one of my thermostats:

![image](https://user-images.githubusercontent.com/18319734/43339619-d85c1a74-91a7-11e8-91ec-4da3c3bb19ef.png)

Instead of having just those entities, I would much rather have other custom cards, e.g,, a [gauge card](https://github.com/helto4real/lovelace-custom-cards/tree/master/src/canvas-gauge-card) or a [thermostat card](https://github.com/ciotlosm/custom-lovelace/tree/test_thermo/thermostat-card). 

I am looking at the glance card as just a way to organize information. It is slightly better way to organize cards than the horizontal stack card (which results in unnecessary white space), but essentially has the same utility. 

We may still want to include a remote card, but I still feel there is a need for this functionality.

**Comment by balloob** [comment] 2018-07-27 19:37
So like a horizontal stack but wrapped inside a card? I think the issue is that right now, we don't have any built in widgets that would work with. The examples you use are all custom ones.

**Comment by arsaboo** [comment] 2018-07-27 21:41
Actually, we could even use picture-entity card inside Glance.

**Comment by helto4real** [comment] 2018-07-28 19:01
I totally support this idea too. Would be great to achieve this.

**Comment by balloob** [comment] 2018-07-30 20:11
Stop calling it glance. Come up with a new proposal for a card.

**Comment by balloob** [comment] 2018-08-02 16:00
I'm going to close this issue. In the current request, adding things to Glance, is not going to happen. The ideas in this issue are also all over the place, making this issue unusable. I'll close it and you can open a new one that is narrower scoped.

**Closed by balloob** 2018-08-02 16:00 UTC
