### ISSUE TITLE
Why is text on entity-button always uppercase? 

### ISSUE THREAD

**Issue by zombiehunter1** [home-assistant/ui-schema#232] opened 2019-01-28 07:39 UTC
Been adding some entity buttons for some reason the button name is always in uppercase 
can I override this, It should display exactly what is in the name attribute 
```
- entity: switch.downstairs_lights
        icon: 'mdi:page-layout-footer'
        name: 'Downstairs Lights' 
        tap_action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: switch.downstairs_lights
        type: entity-button
```

**Comment by wbilger** [comment] 2019-01-29 15:07
That's the default behavior for all or most cards I think.
Can get around it with;
style:
  - text-transform: none

**Comment by zombiehunter1** [comment] 2019-01-29 23:22
Seems an odd choice to ignore the name and friendly_name and just capitalize everything,  We are dealing with a UI presentation not the state machine

**Comment by iantrich** [comment] 2019-01-29 23:40
duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/2407

**Closed by iantrich** 2019-01-29 23:40 UTC
