### ISSUE TITLE
Feature request: Allow entity-filter not states

### ISSUE THREAD

**Issue by MiKuBB** [home-assistant/ui-schema#179] opened 2018-10-19 05:55 UTC
Plz. allow define negated states. 

- type: entity-filter
  entities:
    - device_tracker.demo_paulus
    - device_tracker.demo_anne_therese
    - device_tracker.demo_home_boy
  state_filter:
    - ! home

**Comment by balloob** [comment] 2018-10-19 07:32
duplicate of #177

**Closed by balloob** 2018-10-19 07:32 UTC
