### ISSUE TITLE
[Lovelace] groups with device_trackers are shown as toggle instead of state

### ISSUE THREAD

**Issue by pleeja** [home-assistant/ui-schema#122] opened 2018-07-21 09:37 UTC
This was introduced in 0.74

`person1:
  view: no
  Entities:
    - device_tracker.person1wifi
    - device_tracker.person1gps`
![e9c518d2-f10d-457d-b4eb-0af9481882a7](https://user-images.githubusercontent.com/41104650/43034331-d23648a8-8cda-11e8-8732-d4a0eee4f5ac.jpeg)

**Comment by ciotlosm** [comment] 2018-07-21 11:59
Duplicate of https://github.com/home-assistant/ui-schema/issues/117

**Comment by pleeja** [comment] 2018-07-21 12:03
Same cause? the problem is sort of the other way around.

**Closed** 2018-07-24 06:42 UTC
