### ISSUE TITLE
[lovelace] picture elements, elements positions differ if card title is entered

### ISSUE THREAD

**Issue by Djebouh** [home-assistant/ui-schema#216] opened 2018-12-15 21:24 UTC
The positions were so far only relative to the image (0% was the top of the image), but now, they relate to the complete card (0% is now the top of the card), including the title if specified.
Therefore, if a title is entered, the top alignment is affected (shifted to the top of the image). The initial behavior seems more natural

I am using Home Assistant 0.84.2

**Comment by iantrich** [comment] 2018-12-15 21:30
Duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/2307

**Closed by iantrich** 2018-12-15 21:30 UTC
